module.exports = {
  background: process.env.BACKGROUND || '#303f9f',
  color: process.env.COLOR || '#fafafa',
  title: process.env.TITLE || 'Hello World',
  intro: process.env.INTRO || 'Hello',
  tagline: process.env.TAGLINE || 'World',
  description: process.env.DESCRIPTION || 'Hello World',
  github: process.env.GITHUB,
  twitter: process.env.TWITTER,
  facebook: process.env.FACEBOOK,
  linkedin: process.env.LINKEDIN,
  behance: process.env.BEHANCE,
  devto: process.env.DEVTO,
  medium: process.env.MEDIUM,
  instagram: process.env.INSTAGRAM,
  stackoverflow: process.env.STACKOVERFLOW,
  freecodecamp: process.env.FREECODECAMP,
  codepen: process.env.CODEPEN,
};
